Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
================== RESTART: C:/Users/Joao/Desktop/lista.py ==================
Traceback (most recent call last):
  File "C:/Users/Joao/Desktop/lista.py", line 5, in <module>
    print('QB ', valores[0], valores[1], 'obteve a avaliacao ', valores[10] )
IndexError: list index out of range
>>> 
=============== RESTART: C:/Users/Joao/Desktop/ver lista01.py ===============
>>> joao
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    joao
NameError: name 'joao' is not defined
>>> 
=============== RESTART: C:/Users/Joao/Desktop/ver lista01.py ===============
>>> pedro
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    pedro
NameError: name 'pedro' is not defined
>>> 
=============== RESTART: C:/Users/Joao/Desktop/ver lista01.py ===============
Traceback (most recent call last):
  File "C:/Users/Joao/Desktop/ver lista01.py", line 1, in <module>
    ref_arquivo.close()
NameError: name 'ref_arquivo' is not defined
>>> 
================== RESTART: C:/Users/Joao/Desktop/lista.py ==================
Traceback (most recent call last):
  File "C:/Users/Joao/Desktop/lista.py", line 5, in <module>
    print('QB ', valores[0], valores[1], 'obteve a avaliacao ', valores[10] )
IndexError: list index out of range
>>> 
================== RESTART: C:/Users/Joao/Desktop/lista.py ==================
Traceback (most recent call last):
  File "C:/Users/Joao/Desktop/lista.py", line 5, in <module>
    print('QB ', valores[0], valores[1], 'obteve a avaliacao ', valores[10] )
IndexError: list index out of range
>>> 
============ RESTART: C:/Users/Joao/Desktop/manipular arquivo.py ============
>>> joao
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    joao
NameError: name 'joao' is not defined
>>> josé lima
SyntaxError: invalid syntax
>>> José Lima
SyntaxError: invalid syntax
>>> 
====== RESTART: C:/Users/Joao/Desktop/inserir usuarios em um arquivo.py ======
Traceback (most recent call last):
  File "C:/Users/Joao/Desktop/inserir usuarios em um arquivo.py", line 1, in <module>
    arq = open('/tmp/lista.txt', 'w')
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/lista.txt'
>>> 
====== RESTART: C:/Users/Joao/Desktop/inserir usuarios em um arquivo.py ======
Traceback (most recent call last):
  File "C:/Users/Joao/Desktop/inserir usuarios em um arquivo.py", line 1, in <module>
    arq = open('/tmp/lista.txt', 'w')
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/lista.txt'
>>> 
====== RESTART: C:/Users/Joao/Desktop/inserir usuarios em um arquivo.py ======
>>> 
================ RESTART: C:/Users/Joao/Desktop/ler dados.py ================
Traceback (most recent call last):
  File "C:/Users/Joao/Desktop/ler dados.py", line 1, in <module>
    arq = open('/tmp/lista.txt', 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/lista.txt'
>>> 
================ RESTART: C:/Users/Joao/Desktop/ler dados.py ================
Lista de Alunos
---
João da Silva1
José Lima1
Maria das Dores1
>>> 
